services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGINS=http://localhost:3000
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge